settings:
  legacy:
    force: true
    interval: 1s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: smart_bridge_ark
  path: .
  commands:
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - html
    ignored_paths:
    - .git
    - .realize
    - vendor
    - node_modules
    - /app/assets
