
[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  name = "github.com/dghubble/sling"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kristjank/goark-node"
